#############################################################################
# Makefile for building: MyOpenGL.app/Contents/MacOS/MyOpenGL
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  MyOpenGL.pro
# Template: app
# Command: /Users/colantoni/local/bin/qmake -o Makefile MyOpenGL.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I../../local/lib/QtOpenGL.framework/Versions/5/Headers -I../../local/lib/QtWidgets.framework/Versions/5/Headers -I../../local/lib/QtGui.framework/Versions/5/Headers -I../../local/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../local/mkspecs/macx-clang -F/Users/colantoni/local/lib
QMAKE         = /Users/colantoni/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MyOpenGL1.0.0
DISTDIR = /Users/colantoni/Downloads/MyOpenGL/.tmp/MyOpenGL1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/colantoni/local/lib
LIBS          = $(SUBLIBS) -F/Users/colantoni/local/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		window.cpp \
		myglwidget.cpp moc_window.cpp \
		moc_myglwidget.cpp
OBJECTS       = main.o \
		window.o \
		myglwidget.o \
		moc_window.o \
		moc_myglwidget.o
DIST          = ../../local/mkspecs/features/spec_pre.prf \
		../../local/mkspecs/qdevice.pri \
		../../local/mkspecs/features/device_config.prf \
		../../local/mkspecs/common/shell-unix.conf \
		../../local/mkspecs/common/unix.conf \
		../../local/mkspecs/common/mac.conf \
		../../local/mkspecs/common/macx.conf \
		../../local/mkspecs/common/gcc-base.conf \
		../../local/mkspecs/common/gcc-base-mac.conf \
		../../local/mkspecs/common/clang.conf \
		../../local/mkspecs/common/clang-mac.conf \
		../../local/mkspecs/qconfig.pri \
		../../local/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../local/mkspecs/modules/qt_lib_clucene_private.pri \
		../../local/mkspecs/modules/qt_lib_concurrent.pri \
		../../local/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../local/mkspecs/modules/qt_lib_core.pri \
		../../local/mkspecs/modules/qt_lib_core_private.pri \
		../../local/mkspecs/modules/qt_lib_dbus.pri \
		../../local/mkspecs/modules/qt_lib_dbus_private.pri \
		../../local/mkspecs/modules/qt_lib_designer.pri \
		../../local/mkspecs/modules/qt_lib_designer_private.pri \
		../../local/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../local/mkspecs/modules/qt_lib_gui.pri \
		../../local/mkspecs/modules/qt_lib_gui_private.pri \
		../../local/mkspecs/modules/qt_lib_help.pri \
		../../local/mkspecs/modules/qt_lib_help_private.pri \
		../../local/mkspecs/modules/qt_lib_network.pri \
		../../local/mkspecs/modules/qt_lib_network_private.pri \
		../../local/mkspecs/modules/qt_lib_opengl.pri \
		../../local/mkspecs/modules/qt_lib_opengl_private.pri \
		../../local/mkspecs/modules/qt_lib_openglextensions.pri \
		../../local/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../local/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../local/mkspecs/modules/qt_lib_printsupport.pri \
		../../local/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../local/mkspecs/modules/qt_lib_sql.pri \
		../../local/mkspecs/modules/qt_lib_sql_private.pri \
		../../local/mkspecs/modules/qt_lib_testlib.pri \
		../../local/mkspecs/modules/qt_lib_testlib_private.pri \
		../../local/mkspecs/modules/qt_lib_uitools.pri \
		../../local/mkspecs/modules/qt_lib_uitools_private.pri \
		../../local/mkspecs/modules/qt_lib_widgets.pri \
		../../local/mkspecs/modules/qt_lib_widgets_private.pri \
		../../local/mkspecs/modules/qt_lib_xml.pri \
		../../local/mkspecs/modules/qt_lib_xml_private.pri \
		../../local/mkspecs/features/qt_functions.prf \
		../../local/mkspecs/features/qt_config.prf \
		../../local/mkspecs/macx-clang/qmake.conf \
		../../local/mkspecs/features/spec_post.prf \
		../../local/mkspecs/features/exclusive_builds.prf \
		../../local/mkspecs/features/default_pre.prf \
		../../local/mkspecs/features/mac/default_pre.prf \
		../../local/mkspecs/features/resolve_config.prf \
		../../local/mkspecs/features/default_post.prf \
		../../local/mkspecs/features/mac/sdk.prf \
		../../local/mkspecs/features/mac/default_post.prf \
		../../local/mkspecs/features/mac/objective_c.prf \
		../../local/mkspecs/features/warn_on.prf \
		../../local/mkspecs/features/qt.prf \
		../../local/mkspecs/features/resources.prf \
		../../local/mkspecs/features/moc.prf \
		../../local/mkspecs/features/unix/opengl.prf \
		../../local/mkspecs/features/uic.prf \
		../../local/mkspecs/features/unix/thread.prf \
		../../local/mkspecs/features/mac/rez.prf \
		../../local/mkspecs/features/testcase_targets.prf \
		../../local/mkspecs/features/exceptions.prf \
		../../local/mkspecs/features/yacc.prf \
		../../local/mkspecs/features/lex.prf \
		MyOpenGL.pro window.h \
		myglwidget.h main.cpp \
		window.cpp \
		myglwidget.cpp
QMAKE_TARGET  = MyOpenGL
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = MyOpenGL.app/Contents/MacOS/MyOpenGL

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_window.h $(OBJECTS)  
	@test -d MyOpenGL.app/Contents/MacOS/ || mkdir -p MyOpenGL.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MyOpenGL.pro ../../local/mkspecs/macx-clang/qmake.conf ../../local/mkspecs/features/spec_pre.prf \
		../../local/mkspecs/qdevice.pri \
		../../local/mkspecs/features/device_config.prf \
		../../local/mkspecs/common/shell-unix.conf \
		../../local/mkspecs/common/unix.conf \
		../../local/mkspecs/common/mac.conf \
		../../local/mkspecs/common/macx.conf \
		../../local/mkspecs/common/gcc-base.conf \
		../../local/mkspecs/common/gcc-base-mac.conf \
		../../local/mkspecs/common/clang.conf \
		../../local/mkspecs/common/clang-mac.conf \
		../../local/mkspecs/qconfig.pri \
		../../local/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../local/mkspecs/modules/qt_lib_clucene_private.pri \
		../../local/mkspecs/modules/qt_lib_concurrent.pri \
		../../local/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../local/mkspecs/modules/qt_lib_core.pri \
		../../local/mkspecs/modules/qt_lib_core_private.pri \
		../../local/mkspecs/modules/qt_lib_dbus.pri \
		../../local/mkspecs/modules/qt_lib_dbus_private.pri \
		../../local/mkspecs/modules/qt_lib_designer.pri \
		../../local/mkspecs/modules/qt_lib_designer_private.pri \
		../../local/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../local/mkspecs/modules/qt_lib_gui.pri \
		../../local/mkspecs/modules/qt_lib_gui_private.pri \
		../../local/mkspecs/modules/qt_lib_help.pri \
		../../local/mkspecs/modules/qt_lib_help_private.pri \
		../../local/mkspecs/modules/qt_lib_network.pri \
		../../local/mkspecs/modules/qt_lib_network_private.pri \
		../../local/mkspecs/modules/qt_lib_opengl.pri \
		../../local/mkspecs/modules/qt_lib_opengl_private.pri \
		../../local/mkspecs/modules/qt_lib_openglextensions.pri \
		../../local/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../local/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../local/mkspecs/modules/qt_lib_printsupport.pri \
		../../local/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../local/mkspecs/modules/qt_lib_sql.pri \
		../../local/mkspecs/modules/qt_lib_sql_private.pri \
		../../local/mkspecs/modules/qt_lib_testlib.pri \
		../../local/mkspecs/modules/qt_lib_testlib_private.pri \
		../../local/mkspecs/modules/qt_lib_uitools.pri \
		../../local/mkspecs/modules/qt_lib_uitools_private.pri \
		../../local/mkspecs/modules/qt_lib_widgets.pri \
		../../local/mkspecs/modules/qt_lib_widgets_private.pri \
		../../local/mkspecs/modules/qt_lib_xml.pri \
		../../local/mkspecs/modules/qt_lib_xml_private.pri \
		../../local/mkspecs/features/qt_functions.prf \
		../../local/mkspecs/features/qt_config.prf \
		../../local/mkspecs/macx-clang/qmake.conf \
		../../local/mkspecs/features/spec_post.prf \
		../../local/mkspecs/features/exclusive_builds.prf \
		../../local/mkspecs/features/default_pre.prf \
		../../local/mkspecs/features/mac/default_pre.prf \
		../../local/mkspecs/features/resolve_config.prf \
		../../local/mkspecs/features/default_post.prf \
		../../local/mkspecs/features/mac/sdk.prf \
		../../local/mkspecs/features/mac/default_post.prf \
		../../local/mkspecs/features/mac/objective_c.prf \
		../../local/mkspecs/features/warn_on.prf \
		../../local/mkspecs/features/qt.prf \
		../../local/mkspecs/features/resources.prf \
		../../local/mkspecs/features/moc.prf \
		../../local/mkspecs/features/unix/opengl.prf \
		../../local/mkspecs/features/uic.prf \
		../../local/mkspecs/features/unix/thread.prf \
		../../local/mkspecs/features/mac/rez.prf \
		../../local/mkspecs/features/testcase_targets.prf \
		../../local/mkspecs/features/exceptions.prf \
		../../local/mkspecs/features/yacc.prf \
		../../local/mkspecs/features/lex.prf \
		MyOpenGL.pro \
		/Users/colantoni/local/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/colantoni/local/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/colantoni/local/lib/QtGui.framework/QtGui.prl \
		/Users/colantoni/local/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile MyOpenGL.pro
../../local/mkspecs/features/spec_pre.prf:
../../local/mkspecs/qdevice.pri:
../../local/mkspecs/features/device_config.prf:
../../local/mkspecs/common/shell-unix.conf:
../../local/mkspecs/common/unix.conf:
../../local/mkspecs/common/mac.conf:
../../local/mkspecs/common/macx.conf:
../../local/mkspecs/common/gcc-base.conf:
../../local/mkspecs/common/gcc-base-mac.conf:
../../local/mkspecs/common/clang.conf:
../../local/mkspecs/common/clang-mac.conf:
../../local/mkspecs/qconfig.pri:
../../local/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../local/mkspecs/modules/qt_lib_clucene_private.pri:
../../local/mkspecs/modules/qt_lib_concurrent.pri:
../../local/mkspecs/modules/qt_lib_concurrent_private.pri:
../../local/mkspecs/modules/qt_lib_core.pri:
../../local/mkspecs/modules/qt_lib_core_private.pri:
../../local/mkspecs/modules/qt_lib_dbus.pri:
../../local/mkspecs/modules/qt_lib_dbus_private.pri:
../../local/mkspecs/modules/qt_lib_designer.pri:
../../local/mkspecs/modules/qt_lib_designer_private.pri:
../../local/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../local/mkspecs/modules/qt_lib_gui.pri:
../../local/mkspecs/modules/qt_lib_gui_private.pri:
../../local/mkspecs/modules/qt_lib_help.pri:
../../local/mkspecs/modules/qt_lib_help_private.pri:
../../local/mkspecs/modules/qt_lib_network.pri:
../../local/mkspecs/modules/qt_lib_network_private.pri:
../../local/mkspecs/modules/qt_lib_opengl.pri:
../../local/mkspecs/modules/qt_lib_opengl_private.pri:
../../local/mkspecs/modules/qt_lib_openglextensions.pri:
../../local/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../local/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../local/mkspecs/modules/qt_lib_printsupport.pri:
../../local/mkspecs/modules/qt_lib_printsupport_private.pri:
../../local/mkspecs/modules/qt_lib_sql.pri:
../../local/mkspecs/modules/qt_lib_sql_private.pri:
../../local/mkspecs/modules/qt_lib_testlib.pri:
../../local/mkspecs/modules/qt_lib_testlib_private.pri:
../../local/mkspecs/modules/qt_lib_uitools.pri:
../../local/mkspecs/modules/qt_lib_uitools_private.pri:
../../local/mkspecs/modules/qt_lib_widgets.pri:
../../local/mkspecs/modules/qt_lib_widgets_private.pri:
../../local/mkspecs/modules/qt_lib_xml.pri:
../../local/mkspecs/modules/qt_lib_xml_private.pri:
../../local/mkspecs/features/qt_functions.prf:
../../local/mkspecs/features/qt_config.prf:
../../local/mkspecs/macx-clang/qmake.conf:
../../local/mkspecs/features/spec_post.prf:
../../local/mkspecs/features/exclusive_builds.prf:
../../local/mkspecs/features/default_pre.prf:
../../local/mkspecs/features/mac/default_pre.prf:
../../local/mkspecs/features/resolve_config.prf:
../../local/mkspecs/features/default_post.prf:
../../local/mkspecs/features/mac/sdk.prf:
../../local/mkspecs/features/mac/default_post.prf:
../../local/mkspecs/features/mac/objective_c.prf:
../../local/mkspecs/features/warn_on.prf:
../../local/mkspecs/features/qt.prf:
../../local/mkspecs/features/resources.prf:
../../local/mkspecs/features/moc.prf:
../../local/mkspecs/features/unix/opengl.prf:
../../local/mkspecs/features/uic.prf:
../../local/mkspecs/features/unix/thread.prf:
../../local/mkspecs/features/mac/rez.prf:
../../local/mkspecs/features/testcase_targets.prf:
../../local/mkspecs/features/exceptions.prf:
../../local/mkspecs/features/yacc.prf:
../../local/mkspecs/features/lex.prf:
MyOpenGL.pro:
/Users/colantoni/local/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/colantoni/local/lib/QtWidgets.framework/QtWidgets.prl:
/Users/colantoni/local/lib/QtGui.framework/QtGui.prl:
/Users/colantoni/local/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MyOpenGL.pro

qmake_all: FORCE

MyOpenGL.app/Contents/PkgInfo: 
	@test -d MyOpenGL.app/Contents || mkdir -p MyOpenGL.app/Contents
	@$(DEL_FILE) MyOpenGL.app/Contents/PkgInfo
	@echo "APPL????" >MyOpenGL.app/Contents/PkgInfo
MyOpenGL.app/Contents/Resources/empty.lproj: 
	@test -d MyOpenGL.app/Contents/Resources || mkdir -p MyOpenGL.app/Contents/Resources
	@touch MyOpenGL.app/Contents/Resources/empty.lproj
	
MyOpenGL.app/Contents/Info.plist: 
	@test -d MyOpenGL.app/Contents || mkdir -p MyOpenGL.app/Contents
	@$(DEL_FILE) MyOpenGL.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.MyOpenGL,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,MyOpenGL,g" -e "s,@TYPEINFO@,????,g" ../../local/mkspecs/macx-clang/Info.plist.app >MyOpenGL.app/Contents/Info.plist

all: Makefile \
		MyOpenGL.app/Contents/PkgInfo \
		MyOpenGL.app/Contents/Resources/empty.lproj \
		MyOpenGL.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents window.h myglwidget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp window.cpp myglwidget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents window.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r MyOpenGL.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_window.cpp moc_myglwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_myglwidget.cpp
moc_window.cpp: ../../local/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		window.h
	/Users/colantoni/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/colantoni/local/mkspecs/macx-clang -I/Users/colantoni/Downloads/MyOpenGL -I/Users/colantoni/local/lib/QtOpenGL.framework/Headers -I/Users/colantoni/local/lib/QtWidgets.framework/Headers -I/Users/colantoni/local/lib/QtGui.framework/Headers -I/Users/colantoni/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -F/Users/colantoni/local/lib window.h -o moc_window.cpp

moc_myglwidget.cpp: ../../local/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		myglwidget.h
	/Users/colantoni/local/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/colantoni/local/mkspecs/macx-clang -I/Users/colantoni/Downloads/MyOpenGL -I/Users/colantoni/local/lib/QtOpenGL.framework/Headers -I/Users/colantoni/local/lib/QtWidgets.framework/Headers -I/Users/colantoni/local/lib/QtGui.framework/Headers -I/Users/colantoni/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include -F/Users/colantoni/local/lib myglwidget.h -o moc_myglwidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_window.h
ui_window.h: window.ui \
		myglwidget.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h
	/Users/colantoni/local/bin/uic window.ui -o ui_window.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../local/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		window.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qslider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp ../../local/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/complexwidgets.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/itemviews.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblemenu.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidgets.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/rangecontrols.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/simplewidgets.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		window.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/QSlider \
		ui_window.h \
		myglwidget.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

myglwidget.o: myglwidget.cpp ../../local/lib/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/complexwidgets.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/itemviews.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblemenu.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaccessiblewidgets.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/rangecontrols.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/simplewidgets.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdial.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qframe.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qslider.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		../../local/lib/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/QtOpenGL \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qgl.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qglbuffer.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qglcolormap.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qglframebufferobject.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qglfunctions.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qglpixelbuffer.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qglshaderprogram.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qtopenglglobal.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/qtopenglversion.h \
		myglwidget.h \
		../../local/lib/QtOpenGL.framework/Versions/5/Headers/QGLWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myglwidget.o myglwidget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_myglwidget.o: moc_myglwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myglwidget.o moc_myglwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

